UI
DrewUniversityCS/CS3 pull request #9
Opened 2021-02-23 19:44 UTC by malminawi

2021-02-23 20:05 UTC, NullDefault requested changes

2021-02-23 20:05 UTC, NullDefault commented on pages/urls.py
> +    path('management', page_views.ManagementView.as_view(), name='management'),
I feel like this could be more communicative. I'm assuming this is for data management, so perhaps we can use something along the lines of "vault" or "storage". Maybe call it database and DatabaseView?

2021-02-23 20:05 UTC, NullDefault commented on pages/views.py
> +    template_name = "account/newAdminRegistrationForm.html"
We should enforce standard naming conventions. Are we using camelCase or snake-case?

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/management.html
> +                            <svg xmlns="http://www.w3.org/2000/svg" fill="white" viewBox="0 0 24 24" stroke="#fb2c2c"
These should not be in the middle of the html. You can put them in their own file. See static/icons for an example

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +<!DOCTYPE html>
this seems out of place. stuff like <DOCTYPE> and <head> are all in their own file. See templates/_base.html
To allow other files to use it, add {% extends '_base.html' %} at the top

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +	<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
yeah we should definitely not be importing tailwind here, this defeats the whole point of django-tailwind

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
this is build into our existing tailwind

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +		<form action="#" method="POST">
Did you test if the post request works? I'm curious if we can make use of this down the line

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +                        <div class="flex items-start">
your indentation is all over the place - I recommend using pycharm to enforce styling. Choose Code from the top menu, then Reformat Code: I do it every time before I commit a file.

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +						  <div class="flex items-start">
This is obviously fine for now, but if you could move this to a separate file and make it into a reusable component that would be great.

2021-02-23 20:05 UTC, NullDefault commented on templates/pages/student-form.html
> +  <script>
I think we should keep all our javascript in separate files. This will get out of hand quickly otherwise

2021-02-23 20:07 UTC, NullDefault commented on templates/pages/student-form.html
> +<!DOCTYPE html>
lmao the html tags I wrote dissapeared. I meant to say "<DOCTYPE>" and "<title>"

2021-02-23 20:07 UTC, NullDefault commented on templates/pages/student-form.html
> +<!DOCTYPE html>
DOCTYPE

2021-02-23 20:12 UTC, NullDefault commented on pages/urls.py
> +    path('management', page_views.ManagementView.as_view(), name='management'),
My vote is for
```path('crud', page_views.CrudView.as_view(), name='crud')```

2021-02-23 20:12 UTC, NullDefault commented on templates/pages/management.html
> +
The page looks great! We need to break it down into functional components though. It's going to be very tough to write this page if all the functionality is going to be in one template.

2021-02-24 05:21 UTC, malminawi commented on templates/pages/student-form.html
> +		<form action="#" method="POST">
it is not working yet. its just a UI

2021-03-03 20:58 UTC, merged